services:
  - type: web
    name: medresource-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /assets/*
        destination: /assets/*
      - type: rewrite
        source: /*
        destination: /index.html
    pullRequestPreviewsEnabled: true
    autoDeploy: true